# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e41427b14d399dd7156ea7418dc11de063ec68d7b96fc8db8f197c66bbc5f1c7a61d0d75debe8dbc63c21bac5d760de862ccffeafe164251cf7b5484a8dc97a3

test:
  secret_key_base: acb0f621f824cba82d77d0ddec94c0c2d7992a1acc3bb61cfd377dbfd1c328e2db5435473b5e752a9ce4c2b2cc5e6c98afaaf571691df540a597d44958803e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
